import React from "react";
import MOLECULESTABLEHEADERDEFAULTLEFTALIG from "../MOLECULESTABLEHEADERDEFAULTLEFTALIG";
import ATOMSTABLEBODYCELLDATALEFTALIGNED from "../ATOMSTABLEBODYCELLDATALEFTALIGNED";
import "./MOLECULESTABLECOLUMN10.sass";

class MOLECULESTABLECOLUMN10 extends React.Component {
  render() {
    const {
      className,
      mOLECULESTABLEHEADERDEFAULTLEFTALIG,
      aTOMSTABLEBODYCELLDATALEFTALIGNED1P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED2P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED3P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED4P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED5P,
    } = this.props;

    return (
      <div className={`moleculestablecolumn2-copy-2 ${className || ""}`}>
        <MOLECULESTABLEHEADERDEFAULTLEFTALIG className={mOLECULESTABLEHEADERDEFAULTLEFTALIG.className}>
          {mOLECULESTABLEHEADERDEFAULTLEFTALIG.children}
        </MOLECULESTABLEHEADERDEFAULTLEFTALIG>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED1P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED1P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED2P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED2P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED3P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED3P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED4P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED4P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED5P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED5P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
      </div>
    );
  }
}

export default MOLECULESTABLECOLUMN10;
