import React from "react";
import MOLECULESTABLEHEADERDEFAULTLEFTALIG from "../MOLECULESTABLEHEADERDEFAULTLEFTALIG";
import ATOMSTABLEBODYCELLDATALEFTALIGNED from "../ATOMSTABLEBODYCELLDATALEFTALIGNED";
import "./MOLECULESTABLECOLUMN103.sass";

class MOLECULESTABLECOLUMN103 extends React.Component {
  render() {
    const {
      className,
      mOLECULESTABLEHEADERDEFAULTLEFTALIG,
      aTOMSTABLEBODYCELLDATALEFTALIGNED1P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED2P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED3P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED4P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED5P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED6P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED7P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED8P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED9P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED10,
    } = this.props;

    return (
      <div className={`moleculestablecolumn2-copy-1 ${className || ""}`}>
        <MOLECULESTABLEHEADERDEFAULTLEFTALIG className={mOLECULESTABLEHEADERDEFAULTLEFTALIG.className}>
          {mOLECULESTABLEHEADERDEFAULTLEFTALIG.children}
        </MOLECULESTABLEHEADERDEFAULTLEFTALIG>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED1P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED1P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED2P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED2P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED3P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED3P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED4P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED4P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED5P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED5P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED6P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED6P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED7P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED7P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED8P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED8P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED9P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED9P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED className={aTOMSTABLEBODYCELLDATALEFTALIGNED10.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED10.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED>
      </div>
    );
  }
}

export default MOLECULESTABLECOLUMN103;
