import React from "react";
import MOLECULESTABLEHEADERDEFAULTLEFTALIG from "../MOLECULESTABLEHEADERDEFAULTLEFTALIG";
import ATOMSTABLEBODYCELLDATALEFTALIGNED2 from "../ATOMSTABLEBODYCELLDATALEFTALIGNED2";
import "./MOLECULESTABLECOLUMN104.sass";

class MOLECULESTABLECOLUMN104 extends React.Component {
  render() {
    const {
      mOLECULESTABLEHEADERDEFAULTLEFTALIG,
      aTOMSTABLEBODYCELLDATALEFTALIGNED21,
      aTOMSTABLEBODYCELLDATALEFTALIGNED22,
      aTOMSTABLEBODYCELLDATALEFTALIGNED23,
      aTOMSTABLEBODYCELLDATALEFTALIGNED24,
      aTOMSTABLEBODYCELLDATALEFTALIGNED25,
    } = this.props;

    return (
      <div className="moleculestablecolumn2-1">
        <MOLECULESTABLEHEADERDEFAULTLEFTALIG className={mOLECULESTABLEHEADERDEFAULTLEFTALIG.className}>
          {mOLECULESTABLEHEADERDEFAULTLEFTALIG.children}
        </MOLECULESTABLEHEADERDEFAULTLEFTALIG>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED21.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED21.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED22.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED22.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED23.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED23.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED24.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED24.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED25.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED25.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
      </div>
    );
  }
}

export default MOLECULESTABLECOLUMN104;
