import React from "react";
import MOLECULESTABLEHEADERDEFAULTLEFTALIG from "../MOLECULESTABLEHEADERDEFAULTLEFTALIG";
import ATOMSTABLEBODYCELLDATALEFTALIGNED2 from "../ATOMSTABLEBODYCELLDATALEFTALIGNED2";
import "./MOLECULESTABLECOLUMN105.sass";

class MOLECULESTABLECOLUMN105 extends React.Component {
  render() {
    const {
      mOLECULESTABLEHEADERDEFAULTLEFTALIG,
      aTOMSTABLEBODYCELLDATALEFTALIGNED1P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED1P2,
      aTOMSTABLEBODYCELLDATALEFTALIGNED2P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED3P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED4P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED5P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED6P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED7P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED8P,
      aTOMSTABLEBODYCELLDATALEFTALIGNED9P,
    } = this.props;

    return (
      <div className="moleculestablecolumn2">
        <MOLECULESTABLEHEADERDEFAULTLEFTALIG className={mOLECULESTABLEHEADERDEFAULTLEFTALIG.className}>
          {mOLECULESTABLEHEADERDEFAULTLEFTALIG.children}
        </MOLECULESTABLEHEADERDEFAULTLEFTALIG>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED1P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED1P2.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED1P2.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED2P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED2P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED3P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED3P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED4P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED4P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED5P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED5P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED6P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED6P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED7P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED7P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED8P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED8P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
        <ATOMSTABLEBODYCELLDATALEFTALIGNED2 className={aTOMSTABLEBODYCELLDATALEFTALIGNED9P.className}>
          {aTOMSTABLEBODYCELLDATALEFTALIGNED9P.children}
        </ATOMSTABLEBODYCELLDATALEFTALIGNED2>
      </div>
    );
  }
}

export default MOLECULESTABLECOLUMN105;
