import React from "react";
import ATOMSDIVIDERSLINE1PXGRAY2 from "../ATOMSDIVIDERSLINE1PXGRAY2";
import MOLECULESTABLEACTIONICONTEXT from "../MOLECULESTABLEACTIONICONTEXT";
import MOLECULESTABLEACTIONICONTEXT2 from "../MOLECULESTABLEACTIONICONTEXT2";
import MOLECULESTABLEACTIONICONTEXT3 from "../MOLECULESTABLEACTIONICONTEXT3";
import MOLECULESTABLEACTIONBARSETTINGSCONT from "../MOLECULESTABLEACTIONBARSETTINGSCONT";
import MOLECULESTABLEACTIONBARTEMPLATESELE from "../MOLECULESTABLEACTIONBARTEMPLATESELE";
import MOLECULESTABLECOLUMNHEADERNEW from "../MOLECULESTABLECOLUMNHEADERNEW";
import MOLECULESTABLEROWDEFAULTNEW from "../MOLECULESTABLEROWDEFAULTNEW";
import MOLECULESTABLECOLUMN10 from "../MOLECULESTABLECOLUMN10";
import ATOMSDIVIDERSLINE1PXGRAY from "../ATOMSDIVIDERSLINE1PXGRAY";
import "./LocationTableClosed.sass";

class LocationTableClosed extends React.Component {
  render() {
    const {
      label,
      number,
      aTOMSDIVIDERSLINE1PXGRAY21Props,
      mOLECULESTABLEACTIONICONTEXTProps,
      mOLECULESTABLEACTIONICONTEXT2Props,
      mOLECULESTABLEACTIONICONTEXT3Props,
      mOLECULESTABLEACTIONBARSETTINGSCONT,
      aTOMSDIVIDERSLINE1PXGRAY22Props,
      mOLECULESTABLEACTIONBARTEMPLATESELE,
      mOLECULESTABLECOLUMNHEADERNEWProps,
      mOLECULESTABLEROWDEFAULTNEW1Props,
      mOLECULESTABLEROWDEFAULTNEW2Props,
      mOLECULESTABLEROWDEFAULTNEW3Props,
      mOLECULESTABLEROWDEFAULTNEW4Props,
      mOLECULESTABLEROWDEFAULTNEW5Props,
      mOLECULESTABLEROWDEFAULTNEW6Props,
      mOLECULESTABLECOLUMN101Props,
      aTOMSDIVIDERSLINE1PXGRAYProps,
      mOLECULESTABLECOLUMN102Props,
      mOLECULESTABLECOLUMN103Props,
      mOLECULESTABLECOLUMN104Props,
      mOLECULESTABLECOLUMN105Props,
      mOLECULESTABLECOLUMN106Props,
      mOLECULESTABLECOLUMN107Props,
      mOLECULESTABLECOLUMN108Props,
      mOLECULESTABLECOLUMN109Props,
      mOLECULESTABLECOLUMN1010Props,
    } = this.props;

    return (
      <div className="engagements-table-copy">
        <div className="overlap-group10">
          <ATOMSDIVIDERSLINE1PXGRAY2 />
          <ATOMSDIVIDERSLINE1PXGRAY2 className={aTOMSDIVIDERSLINE1PXGRAY21Props.className} />
          <MOLECULESTABLEACTIONICONTEXT edit={mOLECULESTABLEACTIONICONTEXTProps.edit} />
          <MOLECULESTABLEACTIONICONTEXT2 edit={mOLECULESTABLEACTIONICONTEXT2Props.edit} />
          <MOLECULESTABLEACTIONICONTEXT3 edit={mOLECULESTABLEACTIONICONTEXT3Props.edit} />
          <img
            className="atomsicon2019more-horizontal-copy"
            src="/img/atoms-icon-2019-more-horizontal-copy.svg"
            alt="ATOMS/ICON/2019/more-horizontal Copy"
          />
          <MOLECULESTABLEACTIONBARSETTINGSCONT
            mOLECULESINPUTSDROPDOWNCOMPLETEProp={
              mOLECULESTABLEACTIONBARSETTINGSCONT.mOLECULESINPUTSDROPDOWNCOMPLETEProp
            }
            aTOMSICON2019trashProps2={mOLECULESTABLEACTIONBARSETTINGSCONT.aTOMSICON2019trashProps2}
            mOLECULESINPUTSSEARCHDEFAULTProps={mOLECULESTABLEACTIONBARSETTINGSCONT.mOLECULESINPUTSSEARCHDEFAULTProps}
            aTOMSTABLEFILTERDEFAULTProps={mOLECULESTABLEACTIONBARSETTINGSCONT.aTOMSTABLEFILTERDEFAULTProps}
          />
          <ATOMSDIVIDERSLINE1PXGRAY2 className={aTOMSDIVIDERSLINE1PXGRAY22Props.className} />
          <MOLECULESTABLEACTIONBARTEMPLATESELE
            mOLECULESTABLEACTIONBARSETTINGSCONT={
              mOLECULESTABLEACTIONBARTEMPLATESELE.mOLECULESTABLEACTIONBARSETTINGSCONT
            }
            aTOMSDIVIDERSLINE1PXGRAYProps={mOLECULESTABLEACTIONBARTEMPLATESELE.aTOMSDIVIDERSLINE1PXGRAYProps}
          />
          <div className="rectangle-14"></div>
          <MOLECULESTABLECOLUMNHEADERNEW
            aTOMSDIVIDERSLINE1PXBLACK1Props={mOLECULESTABLECOLUMNHEADERNEWProps.aTOMSDIVIDERSLINE1PXBLACK1Props}
            aTOMSDIVIDERSLINE1PXBLACK2Props={mOLECULESTABLECOLUMNHEADERNEWProps.aTOMSDIVIDERSLINE1PXBLACK2Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW1Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW1Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            className={mOLECULESTABLEROWDEFAULTNEW2Props.className}
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW2Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW2Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            className={mOLECULESTABLEROWDEFAULTNEW3Props.className}
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW3Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW3Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            className={mOLECULESTABLEROWDEFAULTNEW4Props.className}
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW4Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW4Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            className={mOLECULESTABLEROWDEFAULTNEW5Props.className}
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW5Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW5Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <MOLECULESTABLEROWDEFAULTNEW
            className={mOLECULESTABLEROWDEFAULTNEW6Props.className}
            aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW6Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
            aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW6Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
          />
          <div className="carets">
            <article
              className="atomsicon2019cta-caret"
              src="/img/atoms-icon-2019-cta-caret.svg"
              alt="ATOMS/ICON/2019/CTA-caret"
            />
            <article
              className="atomsicon2019cta-caret-copy"
              src="/img/atoms-icon-2019-cta-caret.svg"
              alt="ATOMS/ICON/2019/CTA-caret Copy 3"
            />
            <article
              className="atomsicon2019cta-caret-copy"
              src="/img/atoms-icon-2019-cta-caret.svg"
              alt="ATOMS/ICON/2019/CTA-caret Copy"
            />
            <article
              className="atomsicon2019cta-caret-copy-2"
              src="/img/atoms-icon-2019-cta-caret.svg"
              alt="ATOMS/ICON/2019/CTA-caret Copy 2"
            />
            <article
              className="atomsicon2019cta-caret-copy-4"
              src="/img/atoms-icon-2019-cta-caret.svg"
              alt="ATOMS/ICON/2019/CTA-caret Copy 4"
            />
          </div>
          <MOLECULESTABLECOLUMN10
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN101Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <ATOMSDIVIDERSLINE1PXGRAY className={aTOMSDIVIDERSLINE1PXGRAYProps.className} />
          <div className="group-17">
            <div className="label-2 neuehaasgroteskdisplaystd-bold-black-12px">{label}</div>
            <div className="number-3">{number}</div>
          </div>
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN102Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN102Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN103Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN103Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN104Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN104Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN105Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN105Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN105Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN105Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN105Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN105Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN105Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN106Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN106Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN106Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN106Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN106Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN106Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN106Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN107Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN107Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN107Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN107Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN107Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN107Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN107Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN108Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN108Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN108Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN108Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN108Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN108Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN108Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN109Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN109Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN109Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN109Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN109Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN109Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN109Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
          <MOLECULESTABLECOLUMN10
            className={mOLECULESTABLECOLUMN1010Props.className}
            mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN1010Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
            aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN1010Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN1010Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN1010Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN1010Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
            aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN1010Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
          />
        </div>
      </div>
    );
  }
}

export default LocationTableClosed;
