import React from "react";
import ATOMSCONTENTCONTAINER from "../ATOMSCONTENTCONTAINER";
import ATOMSDIVIDERSLINE1PXGRAY2 from "../ATOMSDIVIDERSLINE1PXGRAY2";
import MOLECULESTABLEACTIONICONTEXT from "../MOLECULESTABLEACTIONICONTEXT";
import MOLECULESTABLEACTIONICONTEXT2 from "../MOLECULESTABLEACTIONICONTEXT2";
import MOLECULESTABLEACTIONICONTEXT3 from "../MOLECULESTABLEACTIONICONTEXT3";
import MOLECULESTABLEACTIONBARSETTINGSCONT from "../MOLECULESTABLEACTIONBARSETTINGSCONT";
import MOLECULESTABLEACTIONBARTEMPLATESELE from "../MOLECULESTABLEACTIONBARTEMPLATESELE";
import MOLECULESTABLECOLUMNHEADERNEW from "../MOLECULESTABLECOLUMNHEADERNEW";
import MOLECULESTABLEROWDEFAULTNEW from "../MOLECULESTABLEROWDEFAULTNEW";
import ATOMSSCROLLBARVERTICAL from "../ATOMSSCROLLBARVERTICAL";
import MOLECULESTABLECOLUMN104 from "../MOLECULESTABLECOLUMN104";
import MOLECULESTABLECOLUMN10 from "../MOLECULESTABLECOLUMN10";
import ATOMSDIVIDERSLINE1PXGRAY from "../ATOMSDIVIDERSLINE1PXGRAY";
import "./LocalTicketDetails.sass";

class LocalTicketDetails extends React.Component {
  render() {
    const {
      aTOMSCONTENTCONTAINERProps,
      aTOMSDIVIDERSLINE1PXGRAY21Props,
      mOLECULESTABLEACTIONICONTEXTProps,
      mOLECULESTABLEACTIONICONTEXT2Props,
      mOLECULESTABLEACTIONICONTEXT3Props,
      mOLECULESTABLEACTIONBARSETTINGSCONT,
      aTOMSDIVIDERSLINE1PXGRAY22Props,
      mOLECULESTABLEACTIONBARTEMPLATESELE,
      mOLECULESTABLECOLUMNHEADERNEWProps,
      mOLECULESTABLEROWDEFAULTNEW1Props,
      mOLECULESTABLEROWDEFAULTNEW2Props,
      mOLECULESTABLEROWDEFAULTNEW3Props,
      mOLECULESTABLEROWDEFAULTNEW4Props,
      mOLECULESTABLEROWDEFAULTNEW5Props,
      aTOMSSCROLLBARVERTICAL1Props,
      mOLECULESTABLECOLUMN104Props,
      mOLECULESTABLECOLUMN101Props,
      mOLECULESTABLECOLUMN102Props,
      mOLECULESTABLECOLUMN103Props,
      mOLECULESTABLECOLUMN104Props2,
      aTOMSSCROLLBARVERTICAL2Props,
      aTOMSDIVIDERSLINE1PXGRAY1Props,
      aTOMSDIVIDERSLINE1PXGRAY2Props,
    } = this.props;

    return (
      <div className="attachments-copy-5">
        <div className="overlap-group12">
          <ATOMSCONTENTCONTAINER className={aTOMSCONTENTCONTAINERProps.className} />
          <div className="group-2-4">
            <div className="overlap-group11-1">
              <ATOMSDIVIDERSLINE1PXGRAY2 className={aTOMSDIVIDERSLINE1PXGRAY21Props.className} />
              <MOLECULESTABLEACTIONICONTEXT
                edit={mOLECULESTABLEACTIONICONTEXTProps.edit}
                className={mOLECULESTABLEACTIONICONTEXTProps.className}
              />
              <MOLECULESTABLEACTIONICONTEXT2
                edit={mOLECULESTABLEACTIONICONTEXT2Props.edit}
                className={mOLECULESTABLEACTIONICONTEXT2Props.className}
              />
              <MOLECULESTABLEACTIONICONTEXT3
                edit={mOLECULESTABLEACTIONICONTEXT3Props.edit}
                className={mOLECULESTABLEACTIONICONTEXT3Props.className}
              />
              <img
                className="atomsicon2019more-horizontal-copy-2"
                src="/img/atoms-icon-2019-more-horizontal-copy.svg"
                alt="ATOMS/ICON/2019/more-horizontal Copy"
              />
              <MOLECULESTABLEACTIONBARSETTINGSCONT
                className={mOLECULESTABLEACTIONBARSETTINGSCONT.className}
                mOLECULESINPUTSDROPDOWNCOMPLETEProp={
                  mOLECULESTABLEACTIONBARSETTINGSCONT.mOLECULESINPUTSDROPDOWNCOMPLETEProp
                }
                aTOMSICON2019trashProps2={mOLECULESTABLEACTIONBARSETTINGSCONT.aTOMSICON2019trashProps2}
                mOLECULESINPUTSSEARCHDEFAULTProps={
                  mOLECULESTABLEACTIONBARSETTINGSCONT.mOLECULESINPUTSSEARCHDEFAULTProps
                }
                aTOMSTABLEFILTERDEFAULTProps={mOLECULESTABLEACTIONBARSETTINGSCONT.aTOMSTABLEFILTERDEFAULTProps}
              />
              <ATOMSDIVIDERSLINE1PXGRAY2 className={aTOMSDIVIDERSLINE1PXGRAY22Props.className} />
              <MOLECULESTABLEACTIONBARTEMPLATESELE
                className={mOLECULESTABLEACTIONBARTEMPLATESELE.className}
                mOLECULESTABLEACTIONBARSETTINGSCONT={
                  mOLECULESTABLEACTIONBARTEMPLATESELE.mOLECULESTABLEACTIONBARSETTINGSCONT
                }
                aTOMSDIVIDERSLINE1PXGRAYProps={mOLECULESTABLEACTIONBARTEMPLATESELE.aTOMSDIVIDERSLINE1PXGRAYProps}
              />
              <div className="rectangle-21"></div>
              <MOLECULESTABLECOLUMNHEADERNEW
                className={mOLECULESTABLECOLUMNHEADERNEWProps.className}
                aTOMSDIVIDERSLINE1PXBLACK1Props={mOLECULESTABLECOLUMNHEADERNEWProps.aTOMSDIVIDERSLINE1PXBLACK1Props}
                aTOMSDIVIDERSLINE1PXBLACK2Props={mOLECULESTABLECOLUMNHEADERNEWProps.aTOMSDIVIDERSLINE1PXBLACK2Props}
              />
              <MOLECULESTABLEROWDEFAULTNEW
                className={mOLECULESTABLEROWDEFAULTNEW1Props.className}
                aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW1Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
                aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW1Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
              />
              <MOLECULESTABLEROWDEFAULTNEW
                className={mOLECULESTABLEROWDEFAULTNEW2Props.className}
                aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW2Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
                aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW2Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
              />
              <MOLECULESTABLEROWDEFAULTNEW
                className={mOLECULESTABLEROWDEFAULTNEW3Props.className}
                aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW3Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
                aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW3Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
              />
              <MOLECULESTABLEROWDEFAULTNEW
                className={mOLECULESTABLEROWDEFAULTNEW4Props.className}
                aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW4Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
                aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW4Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
              />
              <MOLECULESTABLEROWDEFAULTNEW
                className={mOLECULESTABLEROWDEFAULTNEW5Props.className}
                aTOMSDIVIDERSLINE1PXGRAY21Props={mOLECULESTABLEROWDEFAULTNEW5Props.aTOMSDIVIDERSLINE1PXGRAY21Props}
                aTOMSDIVIDERSLINE1PXGRAY22Props={mOLECULESTABLEROWDEFAULTNEW5Props.aTOMSDIVIDERSLINE1PXGRAY22Props}
              />
              <ATOMSSCROLLBARVERTICAL className={aTOMSSCROLLBARVERTICAL1Props.className} />
              <MOLECULESTABLECOLUMN104
                mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN104Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
                aTOMSTABLEBODYCELLDATALEFTALIGNED21={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED21}
                aTOMSTABLEBODYCELLDATALEFTALIGNED22={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED22}
                aTOMSTABLEBODYCELLDATALEFTALIGNED23={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED23}
                aTOMSTABLEBODYCELLDATALEFTALIGNED24={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED24}
                aTOMSTABLEBODYCELLDATALEFTALIGNED25={mOLECULESTABLECOLUMN104Props.aTOMSTABLEBODYCELLDATALEFTALIGNED25}
              />
              <MOLECULESTABLECOLUMN10
                className={mOLECULESTABLECOLUMN101Props.className}
                mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN101Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
                aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN101Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
              />
              <MOLECULESTABLECOLUMN10
                className={mOLECULESTABLECOLUMN102Props.className}
                mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN102Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
                aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN102Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
              />
              <MOLECULESTABLECOLUMN10
                className={mOLECULESTABLECOLUMN103Props.className}
                mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN103Props.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
                aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN103Props.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
              />
              <MOLECULESTABLECOLUMN10
                className={mOLECULESTABLECOLUMN104Props2.className}
                mOLECULESTABLEHEADERDEFAULTLEFTALIG={mOLECULESTABLECOLUMN104Props2.mOLECULESTABLEHEADERDEFAULTLEFTALIG}
                aTOMSTABLEBODYCELLDATALEFTALIGNED1P={mOLECULESTABLECOLUMN104Props2.aTOMSTABLEBODYCELLDATALEFTALIGNED1P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED2P={mOLECULESTABLECOLUMN104Props2.aTOMSTABLEBODYCELLDATALEFTALIGNED2P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED3P={mOLECULESTABLECOLUMN104Props2.aTOMSTABLEBODYCELLDATALEFTALIGNED3P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED4P={mOLECULESTABLECOLUMN104Props2.aTOMSTABLEBODYCELLDATALEFTALIGNED4P}
                aTOMSTABLEBODYCELLDATALEFTALIGNED5P={mOLECULESTABLECOLUMN104Props2.aTOMSTABLEBODYCELLDATALEFTALIGNED5P}
              />
              <ATOMSSCROLLBARVERTICAL className={aTOMSSCROLLBARVERTICAL2Props.className} />
              <ATOMSDIVIDERSLINE1PXGRAY className={aTOMSDIVIDERSLINE1PXGRAY1Props.className} />
            </div>
          </div>
          <ATOMSDIVIDERSLINE1PXGRAY className={aTOMSDIVIDERSLINE1PXGRAY2Props.className} />
        </div>
      </div>
    );
  }
}

export default LocalTicketDetails;
